### ISSUE TITLE
luamin from bash script not working

### ISSUE THREAD

**Issue by Nukesor** [mathiasbynens/luamin#24]
Hi!

I tried to use luamin in combination with git client hooks, when i ran into an error.

The script looks like this:

        #!/bin/sh
        #
        
        cat file1 file2 file3 > concat.lua
        mkdir -p dist
        luamin -f  concat.lua > minified.lua
        rm concat.lua
        git add dist

After running the hook, the content of `minified.lua` is.
        Error: no such file. (``)

`concat.lua` looks perfectly fine. If I run `luamin -f concat.lua > minified.lua` from commandline i don't get errors as well and the minified file is created as planned.

Bash seems to add a magical empty element to the end of the arguments.
This error should be fixed by checking, if snippet is an empty string in bin/luamin: 55
If i find some time, I'll test it on my own and create a pull request.

greetings

Nuke

**Comment by mathiasbynens** [comment]
You have two spaces in `luamin -f  concat.lua`.

**Comment by Nukesor** [comment]
Hi mathiasbynens,

The second spaces is actually a typo in the issue. In my original script there's only one space and it isn't working, as well.

**Comment by Nukesor** [comment]
Ok.
I can't reopen this issue, but i created a working test case on a branch in our project.
[Minify Test Branch](https://github.com/lovetoys/lovetoys/tree/minify)
There is no double space in my original hook script. Maybe you can take a look at it and see it by yourself.
Run `make test` to commit and reset, to trigger the hook.
