### ISSUE TITLE
New version?

### ISSUE THREAD

**Issue by aecay** [mathiasbynens/luamin#33]
There are already 2 significant bugfixes which are not in the latest release on npm (1b569d08b80b3e8fea5ba3679c6ddb34accc2e0c and 2a08ad431dafc117aa13aa3ce9a005a06c9c2c1f), and #32 would make a third.  It would be helpful for using and recommending this software if a new release could be tagged so that these fixes could be pulled in by npm.  Thanks.

**Comment by mathiasbynens** [comment]
I’ll bump once #32 is merged. Sound good?

**Comment by aecay** [comment]
Yes :)
