### ISSUE TITLE
PHP version?

### ISSUE THREAD

**Issue by dannysmc95** [mathiasbynens/luamin#38]
My question, is would you ever think about making a PHP version of this? As I would love to use this for programs I make to distribute them as a minified version, on an App Store I made.

As I would send the data up via PHP post and then get the return you see, so if you do make something like this please tell me as this would be SUPER useful!

Thanks,

**Comment by mathiasbynens** [comment]
A PHP port of luamin is outside the scope of this project.

But then again, it doesn’t sound like you need one. You could easily create a wrapper around [the `luamin` binary](https://github.com/mathiasbynens/luamin#using-the-luamin-binary) in your language of choice.
