### ISSUE TITLE
Lua version?

### ISSUE THREAD

**Issue by MalkContent** [mathiasbynens/luamin#41]
might sound a bit stupid, but i regularly use the minifier for the minecraft mod OpenComputers which uses lua
already tried to automatically request and pull results from i.e. https://mothereff.in/lua-minifier#local%20test%20%3D%205
but failed (doesn't mean it's not possible)  

anyways, it'd be a treat to have a lua minifier which could be used directly inside the game :)

**Comment by mathiasbynens** [comment]
Have you tried using the command-line version?
