### ISSUE TITLE
Methods not working after parenthetical minification

### ISSUE THREAD

**Issue by smart-node** [mathiasbynens/luamin#69]
Before:
`local Variable = ("Wow! This is so amazing!"):gsub('amazing', 'bad')`

After:
`local a="Wow! This is so amazing!":gsub('amazing','bad')`

(after it doesn't work but before it does, Lua 5.1)

**Comment by xLarry** [comment]
Should be fixed by #63 
```console
$ npm i git+https://github.com/Ayplow/luamin.git
+ luamin@1.0.4
$ npx luamin -c "local Variable = ('Wow! This is so amazing!'):gsub('amazing', 'bad')"
local a=('Wow! This is so amazing!'):gsub('amazing','bad')
```
